import {test,expect} from 'bun:test';
import {readFileSync} from 'node:fs';
import {applySeed,handleContentPublish,handleContentGet,handleContentDelete,handleContentRestore,SchemaRegistry} from 'emdash';
import {runMigrations} from 'emdash/db';
import {testRuntime} from './test-runtime';
import {finalizeThingsSeed} from './finalize-things-seed';
import {localDatabase} from './local-database';
import {policyGraph} from '../src/server/things/graph';
import {pathFor,validateGraph,DEFAULT_DATA} from '../src/lib/things/model';
import {migrateThingsLive} from './things-live-migration';
const item=<T extends object>(r:{success:false;error:{message:string}}|{success:true;data:{item:T;_rev?:string}})=>{if(!r.success)throw new Error(JSON.stringify(r.error));return {...r.data.item,_rev:r.data._rev};};
test('Things save live; Posts retain native drafts; references, stale saves and trash remain safe',async()=>{
 const db=localDatabase(':memory:');await runMigrations(db);
 await applySeed(db,JSON.parse(readFileSync('seed/seed.json','utf8')),{includeContent:true,skipMediaDownload:true});
 await finalizeThingsSeed(db);
 const live=await policyGraph(db);expect(live.length).toBeGreaterThan(15);validateGraph(live);
 const writing=live.find(t=>t.slug==='writing')!;expect(writing.contents.length).toBe(3);
 const thing=live.find(t=>t.primaryFolder===writing.id && t.data.page_source==='post')!;
 expect(thing.postId).toBeTruthy();expect(pathFor(thing,live)).toStartWith('/writing/');
 const runtime=await testRuntime(db);
 const created=item(await runtime.handleContentCreate('things',{slug:'immediate-create',data:{...DEFAULT_DATA,name:'Immediate creation'},status:'draft'}));
 item(await handleContentPublish(db,'things',created.id,{_rev:created._rev}));
 expect((await policyGraph(db)).find(t=>t.id===created.id)?.status).toBe('published');
 const initial=item(await handleContentGet(db,'things',thing.id));
 const saved=item(await runtime.handleContentUpdate('things',thing.id,{data:{name:'Saved live',spawn_x:.1},references:{primary_folder:[],contents:[]},_rev:initial._rev}));
 expect(saved.draftRevisionId).toBeNull();
 expect((await runtime.handleContentUpdate('things',thing.id,{data:{name:'Stale overwrite'},_rev:initial._rev})).success).toBe(false);
 expect((await policyGraph(db)).find(t=>t.id===thing.id)?.data.name).toBe('Saved live');
 expect((await policyGraph(db)).find(t=>t.id===thing.id)?.primaryFolder).toBeNull();
 const post=item(await handleContentGet(db,'posts',thing.postId!));
 const postSaved=item(await runtime.handleContentUpdate('posts',thing.postId!,{data:{title:'Private post title'},_rev:post._rev}));
 expect(postSaved.draftRevisionId).toBeTruthy();
 const {ContentRepository}=await import('emdash');expect((await new ContentRepository(db).findById('posts',thing.postId!))?.data.title).toBe(post.data.title);
 expect((await handleContentDelete(db,'things',thing.id)).success).toBe(true);expect((await policyGraph(db)).some(t=>t.id===thing.id)).toBe(false);
 item(await handleContentRestore(db,'things',thing.id));item(await handleContentPublish(db,'things',thing.id));expect((await policyGraph(db)).some(t=>t.id===thing.id)).toBe(true);
 await db.destroy();
},30000);

test('v2 migration keeps article edits in Posts, promotes Thing properties, and is restartable',async()=>{
 const db=localDatabase(':memory:');await runMigrations(db);
 const seed=JSON.parse(readFileSync('seed/seed.json','utf8'));
 const schema=seed.collections.find((c:{slug:string})=>c.slug==='things');schema.supports=['drafts','revisions','preview','seo'];
 for(const t of seed.content.things){const post=seed.content.posts.find((p:{slug:string})=>t.data.legacy_paths.includes('/blog/'+p.slug));if(post){t.data.page_source='content';t.data.body=post.data.content;t.data.date=post.data.date;}}
 await applySeed(db,seed,{includeContent:true,skipMediaDownload:true});await finalizeThingsSeed(db);
 const old=await policyGraph(db);const article=old.find(t=>t.data.date)!;
 const runtime=await testRuntime(db);
 const pending=item(await runtime.handleContentUpdate('things',article.id,{data:{spawn_x:.2,body:[{_type:'block',_key:'new',children:[{_type:'span',text:'Unpublished article edit',marks:[]}]}]}}));expect(pending.draftRevisionId).toBeTruthy();
 expect(await migrateThingsLive(db)).toMatchObject({posts:3,linked:3,promoted:1});
 const current=(await policyGraph(db)).find(t=>t.id===article.id)!;
 expect(current.data.spawn_x).toBe(.2);expect(current.data.body).toEqual([]);expect(current.postId).toBeTruthy();
 const post=item(await handleContentGet(db,'posts',current.postId!));expect(post.draftRevisionId).toBeTruthy();
 expect((await new SchemaRegistry(db).getCollectionWithFields('things'))?.supports).not.toContain('revisions');
 expect((await new SchemaRegistry(db).getCollectionWithFields('posts'))?.hidden).toBe(false);
 expect(await migrateThingsLive(db)).toEqual({alreadyApplied:true});
 await db.destroy();
},30000);
