import {test,expect} from 'bun:test';
import {readFileSync} from 'node:fs';
import {applySeed,handleContentPublish,handleContentGet,handleContentDelete,handleContentRestore} from 'emdash';
import {runMigrations} from 'emdash/db';
import {testRuntime} from './test-runtime';
import {finalizeThingsSeed} from './finalize-things-seed';
import {localDatabase} from './local-database';
import {policyGraph} from '../src/server/things/graph';
import {pathFor,validateGraph} from '../src/lib/things/model';
const item=<T extends object>(r:{success:false;error:{message:string}}|{success:true;data:{item:T;_rev?:string}})=>{if(!r.success)throw new Error(JSON.stringify(r.error));return {...r.data.item,_rev:r.data._rev};};
test('fresh seed, native drafts, references, optimistic concurrency, trash and restore',async()=>{
 const db=localDatabase(':memory:');await runMigrations(db);
 await applySeed(db,JSON.parse(readFileSync('seed/seed.json','utf8')),{includeContent:true,skipMediaDownload:true});
 await finalizeThingsSeed(db);
 const live=await policyGraph(db);expect(live.length).toBeGreaterThan(15);validateGraph(live);
 const writing=live.find(t=>t.slug==='writing')!;expect(writing.contents.length).toBe(3);
 const post=live.find(t=>t.primaryFolder===writing.id && t.data.kind==='page')!;expect(post).toBeDefined();expect(pathFor(post,live)).toStartWith('/writing/');
 const runtime=await testRuntime(db);
 const initial=item(await handleContentGet(db,'things',post.id));
 const saved=item(await runtime.handleContentUpdate('things',post.id,{data:{name:'Draft private',spawn_x:.1},references:{primary_folder:[],contents:[]},_rev:initial._rev}));
 expect((await runtime.handleContentUpdate('things',post.id,{data:{name:'Stale overwrite'},_rev:initial._rev})).success).toBe(false);
 expect((await policyGraph(db)).find(t=>t.id===post.id)?.data.name).toBe(post.data.name);
 expect((await policyGraph(db,post.id)).find(t=>t.id===post.id)?.data.name).toBe('Draft private');
 expect((await policyGraph(db)).find(t=>t.id===post.id)?.primaryFolder).toBe(writing.id);
 item(await handleContentPublish(db,'things',post.id,{_rev:saved._rev}));
 expect((await policyGraph(db)).find(t=>t.id===post.id)?.data.name).toBe('Draft private');
 expect((await handleContentDelete(db,'things',post.id)).success).toBe(true);expect((await policyGraph(db)).some(t=>t.id===post.id)).toBe(false);
 item(await handleContentRestore(db,'things',post.id));expect((await policyGraph(db,undefined,true)).some(t=>t.id===post.id)).toBe(true);
 await db.destroy();
},30000);
